### PR TITLE
Switch a fixed location to an arbitrary one

### PR DESCRIPTION
**Pull request by kawakami-o3**
T/O

### CODE REVIEW

**Comment by dawsonbotsford** [comment]
Not sure what this is supposed to do, can you describe the change further? I am met with an error upon execution which is breaking to the functionality.

```
dirname: illegal option -- /
usage: dirname path
```

It looks like your change is supposed to hijack the current execution location and `cd`ing to `$0`? In that case that's not the original intent, am I wrong?

**Comment by kawakami-o3** [comment]
I am sorry but I should test more.

I wanted to fix my swim in /home/myaccount/bin. If swim script is not in /usr/local/bin, 'swim update' command does not work. This is the problem which I want to fix.

**Comment by dawsonbotsford** [comment]
Oh, this is a good idea!

So because of your patch-1, `swim update` no longer works, correct? I don't believe `patch-2` is the proper way. How about we tell the users to set `usrDir` globally in their rc file and then always use this to get the `swim` install location?

If you want me to build this I could. Feel free to update your patch-2 though also :+1:

**Comment by dawsonbotsford** [comment]
Closing this for now, I'd be glad to merge this if my comment above is taken into consideration for a refactoring. Just reopen if you make change :+1:

**Pull request closed without merging**
