### PR TITLE
Make an install directory changable

### PR DESCRIPTION
**Pull request by kawakami-o3**
I want to choose an install directory. For example,

  curl -s https://raw.githubusercontent.com/dawsonbotsford/swim/master/install | env usrDir=${HOME}/bin bash

### CODE REVIEW

**Comment by dawsonbotsford** [comment]
Looks awesome, thanks @kawakami-o3! Can you say a sentence or two here about how to make this install directory easily configurable because of your changes? I will add it to the readme :+1:

**Comment by kawakami-o3** [comment]
My change use the default value of bash. The variable, usrDir will be "/usr/local/bin" if usrDir is empty. When you give usrDir a value, it is assigned to usrDir. To do it, I use "env" command. "env" allows you to execute a command with a temporally environment variable.

**Comment by dawsonbotsford** [comment]
That's great, I was not aware `usrDir` works that way. So here is what I am planning on adding to the readme for, do you agree?

===
### Custom Executable location
The default install location of the `swim` executable is `/usr/local/bin`, but if you would like a custom location, simply set the environmental variable named `usrDir`. 

Example: `export usrDir="/usr/sbin"`

**Comment by kawakami-o3** [comment]
Yes, I am. It is the good readme.

**Comment by dawsonbotsford** [comment]
Great, should be updated now and I included a new version bump to 0.4.0! Thanks again

**Pull request merged**
